EXPERIMENT:
  NAME: ""
  TAG: "IAKD,res34,res18"
  PROJECT: "imagenet_IAKD"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 256
DISTILLER:
  TYPE: "IAKD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
IAKD:
  SHAPES: [1,7,14,28,56]
  OUT_SHAPES: [1,7,14,28,56]
  IN_CHANNELS: [64,128,256,512,512]
  OUT_CHANNELS: [64,128,256,512,512]
  STU_PREACT: True
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
