EXPERIMENT:
  NAME: ""
  TAG: "IAKD,res32x4,vgg8"
  PROJECT: "VGG"
DISTILLER:
  TYPE: "IAKD"
  TEACHER: "resnet32x4"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
IAKD:
  SHAPES: [1,4,4,8,16]
  OUT_SHAPES: [1,8,8,16,32]
  IN_CHANNELS: [128,256,512,512,512]
  OUT_CHANNELS: [ 64,128,256,256,256]